
CREATE TABLE scores(
    id NUMBER PRIMARY KEY,
    name VARCHAR2(30) NOT NULL,
    kor NUMBER(3) DEFAULT 0,
    eng NUMBER(3) DEFAULT 0,
    math NUMBER(3) DEFAULT 0,
    total NUMBER(3) DEFAULT 0,
    average NUMBER(5,2)
);

CREATE SEQUENCE id_seq 
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 1000
    NOCACHE
    NOCYCLE;


select * FROM scores;
